src/main/java/uk/gov/caz/psr/dto/VehicleEntranceRequest.java
src/main/java/uk/gov/caz/psr/model/VehicleEntrance.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/psr/controller/VehicleEntranceControllerTest.java
src/test/java/uk/gov/caz/psr/service/VehicleEntranceServiceTest.java

* Updated changeSet which alters `DATE_OF_ENTRANCE` attribute to `CAZ_ENTRY_TIMESTAMP`
* Changed `LocalDate dateOfEntrance` to `LocalDateTime dateTimeOfEntrance`
* Updated swagger documentation
* Updated FE-BE contract (_TODO - no edit rights_)
[CAZ_1354 CARD](https://eaflood.atlassian.net/browse/CAZ-1354)
*Note:*
This change will require database drop and recreation on DEV environment

[CAZ-1354] Updated VehicleEntrance attributes and API specification

---

src/it/java/uk/gov/caz/psr/SuccessPaymentsJourneyTestIT.java
src/it/resources/data/sql/add-vehicle-entrants.sql
src/it/resources/data/sql/clear-all-vehicle-entrants.sql
src/main/java/uk/gov/caz/psr/repository/VehicleEntranceRepository.java
src/main/java/uk/gov/caz/psr/service/FinalizePaymentService.java
src/main/java/uk/gov/caz/psr/service/GetAndUpdatePaymentsService.java
src/test/java/uk/gov/caz/psr/repository/VehicleEntranceRepositoryTest.java
src/test/java/uk/gov/caz/psr/service/FinalizePaymentServiceTest.java
src/test/java/uk/gov/caz/psr/service/GetAndUpdatePaymentsServiceTest.java

Jira Card: https://eaflood.atlassian.net/browse/CAZ-1347
Added new service to inject to successfully finished VehicleEntrantPayments objects vehicleEntratntId if already exists. 
Used in update Payment process.
Added Unit tests
Updated Integration test with a successful path of payment.

[CAZ-1347] Adds Service to connect Payment with existing VehicleEntrants after successful payment

---

src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusRequest.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusResponse.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java

* Implemented `getPaymentStatus` endpoint which responses with some stubbed data
* Added `PaymentStatusRequest` class to represent params
* Added specs for the implemented endpoint
[Link to JIRA Card](https://eaflood.atlassian.net/browse/CAZ-1416)

[CAZ-1416] GET ChargeSettlement endpoint with fake data

---

pom.xml
src/it/java/uk/gov/caz/psr/SuccessPaymentStatusUpdateTestIT.java
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
src/main/java/uk/gov/caz/psr/controller/Headers.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateRequest.java
src/main/java/uk/gov/caz/psr/model/VehicleEntrantPaymentStatusUpdate.java
src/main/java/uk/gov/caz/psr/service/PaymentStatusUpdateService.java
src/main/java/uk/gov/caz/psr/service/exception/MissingVehicleEntrantPaymentException.java
src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
src/test/java/uk/gov/caz/psr/repository/VehicleEntrantPaymentRepositoryTest.java
src/test/java/uk/gov/caz/psr/service/PaymentStatusUpdateServiceTest.java
src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java

Added Service to handle PaymentStatus update for selected Vehicle Entrants
Added Unit Tests
Added Integration Tests
Handled Happy Path of the ChargeSettelment#PUT payment_status
Tested in postman:

[CAZ-1348] Handle happy path of ChargeSettlement PaymentStatus update

---

Makefile
docker/docker-compose.yml
src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
src/it/java/uk/gov/caz/psr/repository/PaymentStatusRepositoryTestIT.java
src/it/resources/data/sql/add-payments-for-payment-status.sql
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentStatus.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusRequest.java
src/main/java/uk/gov/caz/psr/model/PaymentStatus.java
src/main/java/uk/gov/caz/psr/service/ChargeSettlementService.java
src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
src/test/java/uk/gov/caz/psr/service/ChargeSettlementServiceTest.java
src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java

* Implemented `ChargeSettlementService` which calls `paymentStatusRepository` and finds proper `PaymentStatus`
* Implemented endpoint in `ChargeSettlementController`
* Implemented unit and integration tests.
---
* [Link to JIRA Card - CAZ-1414](https://eaflood.atlassian.net/browse/CAZ-1414) - service to handle happy path
* [Link to JIRA Card - CAZ-1418](https://eaflood.atlassian.net/browse/CAZ-1418) - glue endpoint with service and repository to provide complete functionality

[CAZ-1414][CAZ-1418] ChargeSettlementController - integration with service and repository

---

src/main/java/uk/gov/caz/psr/service/PaymentStatusUpdateService.java
src/test/java/uk/gov/caz/psr/service/PaymentStatusUpdateServiceTest.java

QA found a bug that they are not able to update case_reference value during payment_status update.
I've found and fixed the bug that we are not assigning it to the update objects.

[CAZ-1429] Fixes bug with not updating case_reference in PUT payment_status update action

---

src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
src/it/java/uk/gov/caz/psr/GetAndUpdatePaymentStatusTestIT.java
src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
src/it/resources/data/sql/add-payments.sql
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
src/main/java/uk/gov/caz/psr/controller/ExceptionController.java
src/main/java/uk/gov/caz/psr/controller/PaymentsControllerApiSpec.java
src/main/java/uk/gov/caz/psr/controller/VehicleEntrantControllerApiSpec.java
src/main/java/uk/gov/caz/psr/controller/exception/DtoValidationException.java
src/main/java/uk/gov/caz/psr/dto/ErrorResponse.java
src/main/java/uk/gov/caz/psr/dto/ErrorsResponse.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateRequest.java
src/main/java/uk/gov/caz/psr/model/ValidationError.java
src/main/java/uk/gov/caz/psr/repository/VehicleEntrantPaymentRepository.java
src/main/java/uk/gov/caz/psr/repository/exception/NotUniqueVehicleEntrantPaymentFoundException.java
src/main/java/uk/gov/caz/psr/service/PaymentStatusUpdateService.java
src/main/java/uk/gov/caz/psr/service/exception/MissingVehicleEntrantPaymentException.java
src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
src/test/java/uk/gov/caz/psr/controller/VehicleEntrantControllerTest.java
src/test/java/uk/gov/caz/psr/repository/VehicleEntrantPaymentRepositoryTest.java
src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java

Added support for Error path in PUT charge_settelment#paument_status action. 
Added support for Request validation errors in response. 
Handled all possible errors
Added tests.

[CAZ-1349] Handle Error path for PUT payment_status update endpoint

---

src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTestIT.java
src/it/resources/data/sql/charge-settlement/payment-info/test-data.sql
src/main/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoService.java
src/main/java/uk/gov/caz/psr/service/paymentinfo/OmitNotPaidPaymentInfoSpecification.java

* add a new specification that does not include not paid payments
* modify integration tests

CAZ-1627 Filter out unsuccessful payments from payment-info endpoint

---

src/it/resources/data/external/create-payment-response.json
src/it/resources/data/external/dangling/cancelled-payment.json
src/it/resources/data/external/dangling/expired-payment.json
src/it/resources/data/external/dangling/success-payment.json
src/it/resources/data/external/get-payment-response.json
src/main/java/uk/gov/caz/psr/repository/ExternalPaymentsRepository.java

Jira Card: https://eaflood.atlassian.net/browse/CAZ-1436
Updated the text which we send as a description to GOV.UK Pay during payment creation. 
Decided to do it as a simple change of text because we will have a separate card for it during fleets implementation to display a more advanced message. For now Payment Service don't support payments for multiple vrns in single request.

[CAZ-1436] Change Payment Description in GOV.UK PAY

---

src/main/resources/db/changelog/changes/0002-1.0-move-audit-table-to-new-schema.yaml
src/main/resources/db/changelog/rawSql/0002-1.0-create_new_audit_table_schema.sql

Creates a new schema for the audit table and adds triggers to all tables in caz_payment to write to the audit table on insert, update or delete.

Move audit table to new schema

---

src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
src/it/java/uk/gov/caz/psr/SuccessPaymentStatusUpdateTestIT.java
src/it/resources/data/sql/add-payments-for-payment-status.sql
src/it/resources/data/sql/add-payments.sql
src/main/java/uk/gov/caz/psr/service/PaymentStatusUpdateService.java
src/main/java/uk/gov/caz/psr/util/EntrantPaymentStatusUpdateConverter.java
src/test/java/uk/gov/caz/psr/service/PaymentStatusUpdateServiceTest.java

**Introduced changes:**
* When request `PUT /payment-status` tries to update `EntrantPayment` which does not exist - the record is being created with the proper data.
**Additional info:**
* [Link to CAZ-1723 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-1723)

[CAZ-1723] Update Payment Status - when EntrantPayment is missing

---

src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
src/it/java/uk/gov/caz/psr/SuccessPaymentStatusUpdateTestIT.java
src/it/java/uk/gov/caz/psr/repository/PaymentStatusRepositoryTestIT.java
src/it/resources/data/sql/add-payments-for-payment-status.sql
src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
src/main/java/uk/gov/caz/psr/repository/PaymentStatusRepository.java
src/main/java/uk/gov/caz/psr/service/ChargeSettlementService.java
src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
src/test/java/uk/gov/caz/psr/service/ChargeSettlementServiceTest.java

Jira card: https://eaflood.atlassian.net/browse/CAZ-1870
Updated the process to return 404 when EntrantPayment not found. 
Added case to return 404 when EntrantPayment not captured in VCCS and failed payment has been processed. 
Added new test cases.

[CAZ-1870] Return 404 for PaymentStatus

---

src/it/java/uk/gov/caz/psr/GetPaidEntrantPaymentsTestIT.java
src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
src/main/java/uk/gov/caz/psr/controller/PaymentsControllerApiSpec.java
src/main/java/uk/gov/caz/psr/controller/exception/InvalidRequestPayloadException.java
src/main/java/uk/gov/caz/psr/dto/PaidPaymentsRequest.java
src/main/java/uk/gov/caz/psr/dto/PaidPaymentsResponse.java
src/main/java/uk/gov/caz/psr/repository/EntrantPaymentRepository.java
src/main/java/uk/gov/caz/psr/service/GetPaidEntrantPaymentsService.java
src/main/java/uk/gov/caz/psr/util/MapPreservingOrderBuilder.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
src/test/java/uk/gov/caz/psr/repository/EntrantPaymentRepositoryTest.java
src/test/java/uk/gov/caz/psr/service/GetPaidEntrantPaymentsServiceTest.java

* `PaymentsController#getPaidEntrantPayment` action
* `GetPaidEntrantPaymentsService`
* `List<EntrantPayment> findAllPaidByVrnAndDateRangeAndCazId` in `EntrantPaymentRepository`
* Copied parameters validation mechanism from Accounts project
* Javadocs, all unit tests and integration tests.
* [Link to CAZ-1760 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-1760)
**Manual testing**

[CAZ-1760] Double payments prevention

---

src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateRequest.java
src/main/java/uk/gov/caz/psr/dto/validation/constraint/ValueIn.java
src/main/java/uk/gov/caz/psr/dto/validation/constraint/ValueInValidator.java
src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java

Jira card: https://eaflood.atlassian.net/browse/CAZ-1900
Added validation to DTO 
- it validates if the provided value is in specified possible values. 
- updated the type to String to avoid exception on request params mapping when enum value is not exactly the same as defined.

[CAZ-1900] Disallowed to use notPaid paymentStatus in update

---

.drone.yml
ci-cd-resources/subscribe_to_alert_topics.py

Subscribe to serious and emergency alarms. Use support email in prod and operational monitoring email for dev, preprod etc. 
The python script to subscribe to alerts has been refactored and some features added:
- Make use of argparse library for command line arguments
- Python3 not 2
- Unsubscribe flag
- Ignore subscriptions pending confirmation flag
- subprocess module rather than writing to files

Subscribe to only serious alerts, exlude minor

---

src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java

Permit payments to proceed in the event of one being in-flight. 
Inspecting logs this results in:
10/03/2020 19:50:59.302  INFO test 7117 --- [nio-8080-exec-3] u.g.c.p.s.CleanupDanglingPaymentService  : Updating status of payment '5bdf0e5a-6308-11ea-ac89-7fb4a9ffe604' from 'CREATED' to 'STARTED'
10/03/2020 19:50:59.358  INFO test 7117 --- [nio-8080-exec-3] u.g.c.p.s.CleanupDanglingPaymentService  : Processing the dangling payment '5bdf0e5a-6308-11ea-ac89-7fb4a9ffe604' took 535ms
Practically, and as tested locally, this permits a payment to proceed. In the event of later abandonment, this should get picked up by the dangling payments lambda function (as it will later transition to expired/abdandoned)

Permit payments to proceed in the event of one being in-flight

---

src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java

Reverts InformedSolutions/JAQU-CAZ-Payments-API#185 to allow assessment on dangling payment behaviour.

Revert "Permit payments to proceed in the event of one being in-flight"

---

src/it/java/uk/gov/caz/psr/SuccessAddingVehicleEntrantIT.java
src/main/java/uk/gov/caz/psr/controller/DirectDebitPaymentsController.java
src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentMethod.java
src/main/java/uk/gov/caz/psr/service/CreateDirectDebitPaymentService.java
src/main/java/uk/gov/caz/psr/util/DirectDebitPaymentRequestToModelConverter.java
src/test/java/uk/gov/caz/psr/controller/DirectDebitPaymentsControllerTest.java
src/test/java/uk/gov/caz/psr/service/CreateDirectDebitPaymentServiceTest.java
src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java

Fixed 2 bugs: 
1. Wrong payment method in charge settlement API
2. Missing MandateId in payment after DirectDebit Payment.

[CAZ-2251] Fix missing MandateId and wrong payment method

---

src/it/resources/data/json/response/account-direct-debit-mandates-response.json
src/it/resources/data/json/response/direct-debit-mandates-for-caz-response.json
src/it/resources/data/json/response/direct-debit-mandates-response.json
src/main/java/uk/gov/caz/psr/dto/AccountDirectDebitMandatesResponse.java
src/main/java/uk/gov/caz/psr/dto/directdebit/DirectDebitMandatesResponse.java
src/main/java/uk/gov/caz/psr/model/directdebit/Mandate.java
src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitMandatesService.java
src/main/java/uk/gov/caz/psr/util/CleanAirZoneWithMandatesToDtoConverter.java
src/main/java/uk/gov/caz/psr/util/MandatesToDtoConverter.java

This PR returns the date a mandate was created on GET endpoints to allow this to be surfaced in the Fleets UI layer.

[CAZ-2615] Return created date for direct debit mandates

---

pom.xml
src/test/java/uk/gov/caz/psr/service/CleanAirZoneServiceTest.java

Jira card: https://eaflood.atlassian.net/browse/CAZ-2854
Added OperatorName to the response of /payments/clean-air-zones endpoint:

[CAZ-2854] Return Operator name in API response

---

src/it/java/uk/gov/caz/psr/ExternalCallsIT.java
src/it/java/uk/gov/caz/psr/RetrieveSuccessfulPaymentsTestIT.java
src/it/java/uk/gov/caz/psr/journeys/RetrieveSuccessfulPaymentsJourneyAssertion.java
src/it/resources/data/external/get-clean-air-zones.json
src/it/resources/data/json/response/account-users-list-response.json
src/it/resources/data/json/response/direct-debit-mandates-response-without-mandates.json
src/it/resources/data/json/response/direct-debit-mandates-response.json
src/it/resources/data/sql/add-caz-entrant-payments.sql
src/main/java/uk/gov/caz/psr/controller/AccountControllerApiSpec.java
src/main/java/uk/gov/caz/psr/controller/AccountsController.java
src/main/java/uk/gov/caz/psr/dto/SuccessfulPaymentsResponse.java
src/main/java/uk/gov/caz/psr/dto/accounts/AccountUserResponse.java
src/main/java/uk/gov/caz/psr/dto/accounts/AccountUsersResponse.java
src/main/java/uk/gov/caz/psr/model/EnrichedPaymentSummary.java
src/main/java/uk/gov/caz/psr/model/PaginationData.java
src/main/java/uk/gov/caz/psr/model/PaymentSummary.java
src/main/java/uk/gov/caz/psr/model/PaymentToCleanAirZoneMapping.java
src/main/java/uk/gov/caz/psr/repository/AccountsRepository.java
src/main/java/uk/gov/caz/psr/repository/PaymentSummaryRepository.java
src/main/java/uk/gov/caz/psr/repository/PaymentToCleanAirZoneMappingRepository.java
src/main/java/uk/gov/caz/psr/service/RetrieveSuccessfulPaymentsService.java
src/main/resources/application.yml
src/test/java/uk/gov/caz/psr/controller/AccountsControllerTest.java
src/test/java/uk/gov/caz/psr/repository/PaymentSummaryRepositoryTest.java
src/test/java/uk/gov/caz/psr/repository/PaymentToCleanAirZoneMappingRepositoryTest.java
src/test/java/uk/gov/caz/psr/service/RetrieveSuccessfulPaymentsServiceTest.java

**JIRA Card**
https://eaflood.atlassian.net/browse/CAZB-2164
----
**Changes description**
* The following changes exposes endpoint which returns data fetched from VCCS API (clean air zones data), Accounts API (users data) and from the database.
* The whole logic is stored in the `RetrieveSuccessfulPaymentsService` which exposes 2 public methods:
* `retrieveForAccount` - for getting all users data based on provided `accountId`,
* `retrieveForSingleUser` - for getting payments data for a single user associated with the `accountId`
* Data coming from the local database looks as follows:
* Using `PaymentSummaryRepository#getTotalPaymentsCountForUserIds` the pagination data are fetched.
* Using `PaymentSummaryRepository#getPaginatedPaymentSummaryForUserIds` the following payments data are …

[CAZB-2164] AccountsPayments endpoint

---

src/main/resources/db/changelog/changes/0013-1.0-payments-reporting-views.yaml
src/main/resources/db/changelog/rawSql/0013-1.0-payments-reporting-views.sql

https://eaflood.atlassian.net/browse/CAZB-2437
https://eaflood.atlassian.net/browse/CAZB-2450
https://eaflood.atlassian.net/browse/CAZB-2451
There is only one view required as aggregation over time periods can be handled in Quicksight for these metrics - this way the dataset will be as versatile as possible.

[CAZB-2437] [CAZB-2450] [CAZB-2450] Payments reporting views

---

src/main/java/uk/gov/caz/psr/service/EntrantPaymentService.java

* Due to the recent changes the `cazEntryTimestamp` was not always assigned when fetching `EntrantPayment` objects

[CAZB-3439] Added missing timestamp to EntrantPayment

---

src/main/resources/db/changelog/changes/0016-1.0-add-indexes-for-payment-match-queries.yaml
src/main/resources/db/changelog/rawSql/0016-1.0-add-indexes-for-payment-match-queries.sql

To improve query performance, an index is being created here against the payment_id field to avoid sequential scans.
Before:
After (index scan applied):
Whilst this is not suspected to resolve the issue in its entirety, this should help improve response times in duplicate payment prevention both in IOD and the Account Pay service.

[CAZB-3404] Add indexes to payment matches

---

src/main/java/uk/gov/caz/psr/service/ChargeableVehiclesService.java
src/test/java/uk/gov/caz/psr/service/ChargeableVehiclesServiceTest.java

* Fetches `pageSize + 1` VRNs from Accounts API in order to be able to verify if we're fetching the last page.
* The redundant VRN is then removed from results in `chargeableVehiclesToDtoConverter`

[CAZB-3404] Fix last page detection on chargeable-vehicle pagination

---

pom.xml

Update Spring to 2.2.12 release to benefit from performance improvements detailed in release notes at https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes

[CAZB-3871] Update Spring to 2.2.12 release

---

pom.xml
src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java

Prevent Spring double init phase causing service timeout. The default character set override can now also be removed as it has been resolved in 1.5.1 of the aws-serverless-java-container-springboot2 package.

[CAZB-3872] Prevent Spring double init phase causing service timeout

---

pom.xml
src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
src/main/resources/application.yml

This PR updates 2 parts of cold-start log entries. The first is a move to Greenwich.SR6 for the Spring cloud version to remove the following example from log entries (see https://github.com/spring-cloud/spring-cloud-commons/issues/657):
`Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$84298a94] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)`
The second is to reduce noise of the following logs by disabling Redis auto-configuration (given a custom bean for elasticache integration is present) via Spring config:
```
s.d.r.c.RepositoryConfigurationDelegate : …
```

[CAZSM-110] Redis log clean-up

---

src/main/resources/db/changelog/changes/0019-1.0-add-email-confirmation-sent-to-t-payment-table.yaml
src/main/resources/db/changelog/changes/0020-1.0-set_already_existing_email_confirmations_to_true.yaml
src/main/resources/db/changelog/rawSql/0019-1.0-add_email_confirmation_sent_to_t_payment.sql
src/main/resources/db/changelog/rawSql/0020-1.0-populate_email_confirmation_sent.sql

**JIRA Card**:
* https://eaflood.atlassian.net/browse/CAZB-3905
**Problem**: 
* On the ST environment, the migration was causing a timeout (probably because of triggered updates)
* Because of the timeout, the transaction was being rolled back, which effectively meant that the `email_confirmation_sent` column was not added to the table.
**Solution**:
* The migration was split into two - one for the column addition and another one for the population of the values.
* Disabled triggers for the database session.

[CAZB-3905] email_confirmation_sent population fix

---

src/main/java/uk/gov/caz/psr/repository/generatecsv/CsvEntrantPaymentRepository.java

https://eaflood.atlassian.net/browse/CAZB-4266 
Updated the scope of payments returned in payments history export CSV to exclude unsuccessful payments and match data returned for the Payments History view.

[CAZB-4266] Hide Unsuccessful payments in Payments History CSV export
