- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/InitiatePaymentRequest.java
- src/main/java/uk/gov/caz/psr/dto/InitiatePaymentResponse.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
- Added POST /payments endpoint 
- Added tests for the controller
- Added all needed classes. 
Tested in postman: 
Valid params:
Invalid params: 
Missing Correlation ID in headers:
> [CAZ-1230] Added POST /payments endpoint which will be used to create payment in GOV.UK PAY

- pom.xml
- src/main/java/uk/gov/caz/psr/PsrSpringConfig.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/controller/VehicleEntranceController.java
- src/main/java/uk/gov/caz/psr/controller/VehicleEntranceControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/VehicleEntranceRequest.java
- src/main/java/uk/gov/caz/psr/model/VehicleEntrance.java
- src/main/java/uk/gov/caz/psr/repository/VehicleEntranceRepository.java
- src/main/java/uk/gov/caz/psr/service/VehicleEntranceService.java
- src/test/java/uk/gov/caz/psr/controller/VehicleEntranceControllerTest.java
- src/test/java/uk/gov/caz/psr/service/VehicleEntranceServiceTest.java
* move logic that deals with vehicle entrance from payment controller to vehicle entrance controller
* add initial version of the service which calls repository
* adjust code coverage inclusions / exclusions
> CAZ-1237 Add initial service layer

- Makefile
- pom.xml
- src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
- src/test/java/uk/gov/caz/psr/service/InitiatePaymentServiceTest.java
Added tests for InitiatePaymentService
Improved tests for PaymentsController
> [CAZ-1304] Add Unit tests for new actions and services

- src/main/java/uk/gov/caz/psr/Application.java
- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
* narrow down the scanned base packages
> NON-JIRA: Increase application's initialization timeout from 20 to 25s

- pom.xml
- src/main/java/uk/gov/caz/psr/amazonaws/CleanupDanglingPaymentsHandler.java
- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/psr/service/CleanupDanglingPaymentsService.java
* increase application's initialization timeout to 60s
> CAZ-1315: Create a lambda handler for dangling payments

- pom.xml
- src/main/java/uk/gov/caz/psr/model/VehicleEntrance.java
- src/main/java/uk/gov/caz/psr/repository/VehicleEntranceRepository.java
- src/main/resources/db/changelog/changes/0001-1.0-create_inital_schemas_with_audit_log.yaml
- src/test/java/uk/gov/caz/psr/controller/VehicleEntranceControllerTest.java
- src/test/java/uk/gov/caz/psr/repository/VehicleEntranceRepositoryTest.java
- src/test/java/uk/gov/caz/psr/service/VehicleEntranceServiceTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
* Implemented `public void insertIfNotExist(VehicleEntrance vehicleEntrance)` method in `VehicleEntranceRepository`
* Added specs for preconditions
* Updated db schema with `VehicleEntrant#cazEntryDate`
* Updated associated model, `VehicleEntranceRequest` and swagger docs.
---
[Link to JIRA Card](https://eaflood.atlassian.net/browse/CAZ-1238)
> [CAZ-1238] VehicleEntranceRepository

- src/it/java/uk/gov/caz/psr/SuccessAddingVehicleEntrantIT.java
- src/it/java/uk/gov/caz/psr/repository/VehicleEntrantRepositoryTestIT.java
- src/main/java/uk/gov/caz/psr/repository/VehicleEntrantRepository.java
- src/main/java/uk/gov/caz/psr/service/VehicleEntrantService.java
- src/test/java/uk/gov/caz/psr/service/VehicleEntrantServiceTest.java
* restore the version with `ON CONFLICT DO NOTHING` statement
* add integration and unit tests
> NON-JIRA Fix inserting duplicate vehicle entrant entities

- pom.xml
- src/it/java/uk/gov/caz/psr/SuccessAddingVehicleEntrantIT.java
Add fixed security headers to all responses from API endpoints.
> TPDPB-5 - Add fixed security headers to all responses from API endpoints.

- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusResponse.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateRequest.java
- src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Jira Card: https://eaflood.atlassian.net/browse/CAZ-1429
Updated the controller action based on OpenAPI
Added Basic Tests
> [CAZ-1429] Updated PUT /v1/charge-settlement/payment-status endpoint based on Open API

- pom.xml
- src/main/java/uk/gov/caz/psr/repository/VehicleEntrantPaymentRepository.java
- src/main/resources/db/changelog/changes/0002-1.0-create_vehicle_entrant_payment_index.yaml
- src/test/java/uk/gov/caz/psr/repository/VehicleEntrantPaymentRepositoryTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Added findAllBy to VehicleEntrantPaymentRepository to get all VehicleEntrantPayments for provided details.
> [CAZ-1430] Add method findAllBy to VehicleEntrantPaymentRepository

- pom.xml
- src/it/resources/logback-test.xml
- src/main/resources/logback-spring.xml
* update version of the internal libraries version from `1.8.0-SNAPSHOT` to `2.0-SNAPSHOT`
> NON-JIRA Use new logging configuration from the internal `logger` library

- .drone.yml
Updated with localstack step for sit enviornment
> Updated with localstack step for sit enviornment

- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/PaymentInfoRequest.java
- src/main/resources/application.yml
* add `PaymentInfoRequest` class with swagger-annotated fields
* add fields description in `application.yml`
* change formatting of fields description in `application.yml` (break long lines)
> CAZ-1217 Update API specification for charge settlement endpoints

- pom.xml
* update internal common library from `2.0-SNAPSHOT` to `2.5-SNAPSHOT`
* update mock-server from `5.6.1` to `5.7.2`
> NON-JIRA Update spring from `2.1.5.RELEASE` to `2.2.1.RELEASE`

- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentStatus.java
- src/main/java/uk/gov/caz/psr/dto/PaymentInfoResponse.java
- src/main/java/uk/gov/caz/psr/util/VehicleEntrantPaymentInfoConverter.java
- src/test/java/uk/gov/caz/psr/util/VehicleEntrantPaymentInfoConverterTest.java
* change values of payment status to be lowercase and camelcase
* change the attribute name from `chargeSettlementPaymentStatus` to `paymentStatus`
> NON-JIRA Align `payment-info` response with the ICD v1.6

- src/main/resources/db/changelog/changes/0001-1.0-create_inital_schemas_with_audit_log.yaml
Warning! Warning!
Merging this PR will probably require to drop DB tables of Payments-DB
> NON-JIRA If audit log tables exist mark Liquibase change as run

- src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/controller/ExceptionController.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusRequest.java
- src/main/java/uk/gov/caz/psr/service/ChargeSettlementService.java
- src/main/java/uk/gov/caz/psr/service/exception/TooManyPaidPaymentStatusesException.java
- src/main/resources/messages.properties
- src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
* Implemented error handling for `GET PaymentStatus`
* Adjusted tests
[Link to JIRA Card](https://eaflood.atlassian.net/browse/CAZ-1415)
**Testing**
* Tested all possible scenarios with Postman
> [CAZ-1415] Error scenarios for GET payments-status

- src/main/java/uk/gov/caz/psr/controller/VehicleEntrantController.java
- src/main/java/uk/gov/caz/psr/dto/CazEntrantPaymentDto.java
- src/main/java/uk/gov/caz/psr/repository/CazEntrantPaymentRepository.java
- src/main/java/uk/gov/caz/psr/service/CazEntrantPaymentService.java
- src/test/java/uk/gov/caz/psr/repository/CazEntrantPaymentRepositoryTest.java
- src/test/java/uk/gov/caz/psr/service/CazEntrantPaymentServiceTest.java
https://eaflood.atlassian.net/browse/CAZ-1714
> [CAZ-1714] Sync payments when they exists

- .drone.yml
Add localstack secretsmanager env var to SIT integration test steps
> Add localstack secretsmanager env var to SIT integration test steps

- src/it/java/uk/gov/caz/psr/DanglingPaymentsCleanupTestIT.java
- src/it/resources/data/sql/dangling-payments-test-data.sql
- src/main/java/uk/gov/caz/psr/service/CleanupDanglingPaymentService.java
- src/main/java/uk/gov/caz/psr/service/CleanupDanglingPaymentsService.java
- src/test/java/uk/gov/caz/psr/service/CleanupDanglingPaymentServiceTest.java
- src/test/java/uk/gov/caz/psr/service/CleanupDanglingPaymentsServiceTest.java
Jira card: https://eaflood.atlassian.net/browse/CAZ-1727
Updated services with new ERD for Dangling Payment.
> [CAZ-1727] Fix Dangling Payments services for new ERD

- src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
- src/it/resources/data/sql/add-payments-for-payment-status.sql
- src/main/java/uk/gov/caz/psr/service/PaymentStatusUpdateService.java
- src/main/java/uk/gov/caz/psr/service/exception/PaymentNotProcessedException.java
- src/test/java/uk/gov/caz/psr/service/PaymentStatusUpdateServiceTest.java
[CAZ-1725 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-1725)
> [CAZ-1725] PUT /payment-status - pending payment exception

- .drone.yml
> DB var corrections for ST

- .drone.yml
Correct checkout placement for ST pipeline
> Correct checkout placement for ST pipeline

- .drone.yml
Correct workspace for tf plan in ST
> Correct workspace for tf plan in ST

- .drone.yml
> Promote drone pipeline fix

- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/service/GetPaidEntrantPaymentsService.java
- src/test/java/uk/gov/caz/psr/service/GetPaidEntrantPaymentsServiceTest.java
> [NON_JIRA] POST /payments/paid - Change empty response format

- src/main/java/uk/gov/caz/psr/repository/EntrantPaymentRepository.java
- src/main/java/uk/gov/caz/psr/service/CleanupDanglingPaymentService.java
- src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
- src/main/java/uk/gov/caz/psr/service/InitiatePaymentService.java
- src/test/java/uk/gov/caz/psr/service/CleanupDanglingPaymentsServiceTest.java
- src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java
See the description in JIRA: https://eaflood.atlassian.net/browse/CAZ-1921
> CAZ-1921 Unblock abandoned payments

- src/it/java/uk/gov/caz/psr/repository/PaymentRepositoryTestIT.java
- src/main/java/uk/gov/caz/psr/repository/EntrantPaymentRepository.java
- src/main/java/uk/gov/caz/psr/service/CleanupDanglingPaymentService.java
- src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
- src/main/java/uk/gov/caz/psr/service/InitiatePaymentService.java
- src/test/java/uk/gov/caz/psr/service/CleanupDanglingPaymentsServiceTest.java
- src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java
Update ST with latest dev code
> Update ST with latest dev code

- src/it/java/uk/gov/caz/psr/ReconcilePaymentStatusTestIT.java
- src/it/java/uk/gov/caz/psr/SuccessPaymentsJourneyTestIT.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/ReconcilePaymentRequest.java
- src/main/java/uk/gov/caz/psr/service/ReconcilePaymentStatusService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/service/ReconcilePaymentStatusServiceTest.java
This reverts commit 5657653c974a9cc66bf8de3e644500b8a1f62336.
> Revert [CAZ-1877] Remove CAZ name attribute from PUT /payment/{id}

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTestIT.java
- src/main/java/uk/gov/caz/psr/controller/ExceptionController.java
- src/main/java/uk/gov/caz/psr/controller/exception/PaymentInfoVrnValidationException.java
- src/main/java/uk/gov/caz/psr/dto/PaymentInfoErrorResponse.java
- src/main/java/uk/gov/caz/psr/dto/PaymentInfoErrorsResponse.java
- src/main/java/uk/gov/caz/psr/repository/EntrantPaymentRepository.java
- src/main/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoService.java
- src/test/java/uk/gov/caz/psr/model/PaymentTest.java
- src/test/java/uk/gov/caz/psr/repository/EntrantPaymentRepositoryTest.java
Update ST with 404 error response in Charge Settlement API
> Return 400 response if vrn not found (#163)

- src/main/java/uk/gov/caz/psr/repository/AccountsRepository.java
Correct variable for paging and sorting repository on accounts API. A scenario to cover out of bounds requests needs handled in the Accounts API.
> Correct variable for paging and sorting repository on accounts API

- src/main/java/uk/gov/caz/psr/service/VehicleComplianceRetrievalService.java
Increase timeout for vccs compliance check
> Increase timeout for vccs compliance check

- pom.xml
All Spring MVC exceptions, especially REST method validations will be logged as errors. Response body is still empty so will not reveal any details.
> All Spring MVC exceptions, especially REST method validations will be logged as errors. Response body is still empty so will not reveal any details.

- .drone.yml
CAZ-2054 - prod environment drone changes
> CAZ-2054 - prod environment drone changes

- src/main/java/uk/gov/caz/psr/controller/AccountsController.java
- src/main/java/uk/gov/caz/psr/service/AccountService.java
NON-JIRA When chargeable vehicles for fleets is empty it shall not break the service
> NON-JIRA When chargeable vehicles for fleets is empty it shall not break the service

- pom.xml
- src/it/java/uk/gov/caz/psr/ExternalCallsIT.java
- src/it/java/uk/gov/caz/psr/VehicleComplianceIT.java
- src/it/resources/data/json/response/unknown-vehicle-compliance-response.json
- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/repository/VccsRepository.java
- src/main/java/uk/gov/caz/psr/service/VehicleComplianceRetrievalService.java
- src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
Add proxy endpoint for retrieving unknown vehicle compliance
> Add proxy endpoint for retrieving unknown vehicle compliance

- pom.xml
- src/main/java/uk/gov/caz/psr/repository/VccsRepository.java
Add logging to VCCS repository to support diagnostics and test evidence (by dynamically resolving slf4j DI logger implementation).
> Add logging to vccs repository

- src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
- src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java
Allow new payments to be initiated when existing payments are in-flight
> Permit payments to proceed in the event of one being in-flight""

- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
Having observed cold starts in dev, this change mirrors those introduced to VCCS under InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-API#440.
> Adjust lambda initialisation method

- src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
- src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentMethod.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusResponse.java
- src/main/java/uk/gov/caz/psr/model/PaymentStatus.java
- src/main/java/uk/gov/caz/psr/repository/PaymentStatusRepository.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/dto/PaymentStatusResponseTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
[Link to CAZ-2178 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2178)
> [CAZ-2178] ChargeSettlement#getPaymentStatus response update

- src/main/java/uk/gov/caz/psr/dto/PaymentInfoResponse.java
- src/main/java/uk/gov/caz/psr/model/info/PaymentInfo.java
- src/main/java/uk/gov/caz/psr/util/EntrantPaymentInfoConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
[Link to CAZ-2173 JIRA Card](https://eaflood.atlassian.net/browse/CAZ-2173)
> [CAZ-2173] ChargeSettlement#getPaymentInfo response update

- src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentMethod.java
> [CAZ-2251] Fixed PaymentMethod in ChargeSettlement API to be lowercase

- src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
- src/it/resources/data/sql/add-payments-for-payment-status.sql
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusResponse.java
- src/main/java/uk/gov/caz/psr/model/PaymentStatus.java
- src/main/java/uk/gov/caz/psr/model/info/PaymentInfo.java
- src/main/java/uk/gov/caz/psr/repository/PaymentStatusRepository.java
- src/main/java/uk/gov/caz/psr/util/EntrantPaymentInfoConverter.java
- src/test/java/uk/gov/caz/psr/dto/PaymentStatusResponseTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Jira card: https://eaflood.atlassian.net/browse/CAZ-2541
Added support for telephonePayment for ChargeSettlement API
> [CAZ-2541] Support telephonePayment in ChargeSettlement API

- src/it/java/uk/gov/caz/psr/directdebit/DirectDebitJourneyTestIT.java
- src/it/resources/application-integration-tests.yml
- src/main/java/uk/gov/caz/psr/configuration/PaymentReceiptEmailConfiguration.java
- src/main/java/uk/gov/caz/psr/dto/directdebit/CreateDirectDebitPaymentRequest.java
- src/main/java/uk/gov/caz/psr/service/CreateDirectDebitPaymentService.java
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentStatusUpdater.java
- src/main/java/uk/gov/caz/psr/service/listener/PaymentReceiptSender.java
- src/main/java/uk/gov/caz/psr/service/receipt/DirectDebitPaymentReceiptRequestCreator.java
- src/main/java/uk/gov/caz/psr/util/DirectDebitPaymentRequestToModelConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/DirectDebitPaymentsControllerTest.java
- src/test/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentStatusUpdaterTest.java
- src/test/java/uk/gov/caz/psr/service/listener/PaymentReceiptSenderTest.java
Jira card: https://eaflood.atlassian.net/browse/CAZ-2672
Added support for sending email during DirectDebit payment creation.
> [CAZ-2672] Add email on DirectDebit payment

- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
Jira Card: https://eaflood.atlassian.net/browse/CAZ-2660
Remove request information from logs
> [CAZ-2672] Remove request information from logs

- .drone.yml
- pom.xml
- src/it/java/uk/gov/caz/psr/service/audit/PaymentDataCleanupServiceTestIT.java
- src/it/resources/data/sql/clear-data-and-drop-fk-constraint.sql
- src/it/resources/data/sql/re-add-fk-constraint-to-payment-audit-tables.sql
- src/main/java/uk/gov/caz/psr/amazonaws/CleanupOldAuditDataLambdaHandler.java
- src/main/java/uk/gov/caz/psr/repository/audit/PaymentDetailRepository.java
- src/main/java/uk/gov/caz/psr/repository/audit/PaymentLoggedActionRepository.java
- src/main/java/uk/gov/caz/psr/service/audit/PaymentDataCleanupService.java
- src/main/resources/db/changelog/changes/0008-1.0-add-inserttimestamp_to_audit_tables.yaml
- src/test/java/uk/gov/caz/psr/service/audit/PaymentDataCleanupServiceTest.java
Ticket https://eaflood.atlassian.net/browse/CAZ-2710.
Deployment steps:
1. Merge this PR to develop branch
2. Follow by merging this IAC pr https://github.com/InformedSolutions/JAQU-CAZ-IAC/pull/1095
> Remove old payment audit data

- .drone.yml
Fix db schema migrations by setting Alpine to fixed version pre-3.12
> Fix db schema migrations

- src/it/java/uk/gov/caz/psr/RetrieveAccountVehiclesAndChargeabilityIT.java
- src/main/java/uk/gov/caz/psr/service/AccountService.java
Re-throw 400 error if this is raised from Accounts API.
> [CAZ-2723] throw 400 if page supplied is out of bounds

- src/it/java/uk/gov/caz/psr/RetrieveAccountVehiclesAndChargeabilityIT.java
- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/psr/service/AccountService.java
Merge up develop to new AWS account
> Merge up develop to new AWS account

- .github/API-dependabot.yml
Part of the operational calendar to ensure dependancies are kept current
> added dependabot dependancy updates file

- .drone2.yml
Promote v1.2.0 to new AWS pre-prod
> Promote v1.2.0 to new AWS pre-prod

- .drone2.yml
- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTestIT.java
> NON-JIRA Revert "Temp remove integration test step in dev"

- .drone2.yml
> Add clone command to ST deploy step

- src/main/java/uk/gov/caz/psr/model/EnrichedPaymentSummary.java
- src/main/java/uk/gov/caz/psr/model/PaymentSummary.java
- src/main/java/uk/gov/caz/psr/repository/PaymentSummaryRepository.java
- src/main/java/uk/gov/caz/psr/service/RetrieveSuccessfulPaymentsService.java
- src/test/java/uk/gov/caz/psr/controller/AccountsControllerTest.java
- src/test/java/uk/gov/caz/psr/service/RetrieveSuccessfulPaymentsServiceTest.java
JIRA Card - https://eaflood.atlassian.net/browse/CAZB-2164
* Added `paymentDate` to the response 
* Added currency formatting for `totalPaid` field
> [CAZB-2164] Added PaymentDate and changed totalPaid format

- src/it/java/uk/gov/caz/psr/PaymentReceiptSenderTestIT.java
- src/it/resources/application-integration-tests.yml
- src/main/java/uk/gov/caz/psr/service/listener/PaymentReceiptSender.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/service/listener/PaymentReceiptSenderTest.java
https://eaflood.atlassian.net/browse/CAZB-2415
> CAZB-2415 Can ignore specific email(s) when sending payment receipt email

- .drone2.yml
Promote Drone file branch correction
> Promote Drone file branch correction

- .drone2.yml
This reverts commit 31df1a123216f692d5784b57a91da601acfe43a8.
> Revert "re-add plan step (#307)"

- src/it/java/uk/gov/caz/psr/PaymentDetailsTestIT.java
- src/it/java/uk/gov/caz/psr/directdebit/DirectDebitJourneyTestIT.java
- src/it/resources/data/sql/charge-settlement/payment-info/test-data.sql
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentStatusUpdater.java
- src/main/java/uk/gov/caz/psr/util/PaymentDetailsConverter.java
- src/test/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentStatusUpdaterTest.java
Reverts InformedSolutions/JAQU-CAZ-Payments-API#314
> Revert "Promote develop to ST v1.3"

- src/it/java/uk/gov/caz/psr/PaymentDetailsTestIT.java
- src/it/java/uk/gov/caz/psr/directdebit/DirectDebitJourneyTestIT.java
- src/it/resources/data/sql/charge-settlement/payment-info/test-data.sql
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentStatusUpdater.java
- src/main/java/uk/gov/caz/psr/util/PaymentDetailsConverter.java
- src/test/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentStatusUpdaterTest.java
Reverts InformedSolutions/JAQU-CAZ-Payments-API#315
> Revert "Revert "Promote develop to ST v1.3""

- src/it/java/uk/gov/caz/psr/VehiclePaymentHistoryControllerTestIT.java
- src/it/java/uk/gov/caz/psr/journeys/VehiclePaymentHistoryJourneyAssertion.java
- src/main/java/uk/gov/caz/psr/dto/VehiclePaymentHistoryResponse.java
CAZB-2556 Return correct page number (that starts from zero)
> CAZB-2556 Return correct page number (that starts from zero)

- src/main/resources/db/changelog/changes/0011-1.0-add-accounts-reporting-views.yaml
- src/main/resources/db/changelog/rawSql/0011-1.0-add-accounts-reporting-views.sql
https://eaflood.atlassian.net/browse/CAZB-2439
https://eaflood.atlassian.net/browse/CAZB-2446
https://eaflood.atlassian.net/browse/CAZB-2447
> [CAZB-2439] [CAZB-2446] [CAZB-2447] Account payments reporting views

- pom.xml
- src/it/java/uk/gov/caz/psr/ExternalCallsIT.java
- src/it/java/uk/gov/caz/psr/RetrieveChargeableAccountVehiclesIT.java
- src/it/java/uk/gov/caz/psr/journeys/RetrieveChargeableAccountVehiclesJourneyAssertion.java
- src/it/resources/data/json/response/account-single-chargeable-vehicles-response.json
- src/it/resources/data/json/response/account-vehicles-cursor-empty-response.json
- src/it/resources/data/json/response/account-vehicles-cursor-previous-response.json
- src/it/resources/data/json/response/account-vehicles-cursor-response.json
- src/it/resources/data/json/response/account-vehicles-not-chargeable-cursor-response.json
- src/main/java/uk/gov/caz/psr/controller/AccountsController.java
- src/main/java/uk/gov/caz/psr/dto/ChargeableAccountVehiclesResult.java
- src/main/java/uk/gov/caz/psr/model/ChargeableVehicle.java
- src/main/java/uk/gov/caz/psr/repository/AccountsRepository.java
- src/main/java/uk/gov/caz/psr/service/AccountService.java
- src/main/java/uk/gov/caz/psr/service/ChargeableVehiclesService.java
- src/main/java/uk/gov/caz/psr/util/ChargeableVehiclesToDtoConverter.java
- src/test/java/uk/gov/caz/psr/controller/AccountsControllerTest.java
- src/test/java/uk/gov/caz/psr/service/ChargeableVehiclesServiceTest.java
Jira card: https://eaflood.atlassian.net/browse/CAZB-3001
> [CAZB-3001] Update chargeable-vehicles endpoint to use cachedCharge

- src/it/java/uk/gov/caz/psr/RetrieveChargeableAccountVehiclesIT.java
- src/it/resources/data/json/response/account-vehicles-previous-cursor-response.json
- src/it/resources/data/json/response/account-vehicles-without-cursor-response.json
- src/main/java/uk/gov/caz/psr/service/ChargeableVehiclesService.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-2932 
Fixes pagination for Payment Matrix page.
> [CAZB-2932] Fix Pagination on payment matrix page

- src/main/resources/application.yml
https://eaflood.atlassian.net/browse/CAZB-3144
> [CAZB-3144] set correlation id logger to info level

- src/main/resources/db/changelog/changes/0013-1.0-payments-reporting-views.yaml
- src/main/resources/db/changelog/changes/0014-1.0-update-payments-reporting-view.yaml
- src/main/resources/db/changelog/rawSql/0013-1.0-payments-reporting-views.sql
- src/main/resources/db/changelog/rawSql/0014-1.0-update-payments-reporting-view.sql
Update the payments reporting view to individual a column to indicate whether the payment was from an individual or an account
> [CAZB-2437] [CAZB-2450] [CAZB-2451] Update payments reporting views

- src/main/java/uk/gov/caz/psr/service/CreateDirectDebitPaymentService.java
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentService.java
- src/test/java/uk/gov/caz/psr/service/CreateDirectDebitPaymentServiceTest.java
- src/test/java/uk/gov/caz/psr/service/directdebit/DirectDebitPaymentServiceTest.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3117
Added payment ID to GoCardless call header. 
Added some missing Tests.
> [CAZB-3117] Payment Idempotency key generation

- src/it/java/uk/gov/caz/psr/SuccessPaymentsJourneyTestIT.java
- src/main/java/uk/gov/caz/psr/controller/exception/EntrantPaymentAlreadyPaidException.java
- src/main/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsService.java
- src/test/java/uk/gov/caz/psr/service/InitiateEntrantPaymentsServiceTest.java
**Link to JIRA Card:**
* https://eaflood.atlassian.net/browse/CAZB-3352
* This part of the solution returns a 422 status with an error message when trying to pay for the already paid entrant.
> [CAZB-3352] Return 422 error on duplicated direct debit payment

- src/main/resources/db/changelog/changes/0015-1.0-add-test-data-generation-procedure.yaml
- src/main/resources/db/changelog/rawSql/0015-1.0-add-test-data-generation-procedure.sql
Add stored procedure for generating synthetic test data
> [CAZB-3382] Add stored procedure for generating synthetic test data

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTestIT.java
- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
- src/main/java/uk/gov/caz/psr/controller/ExceptionController.java
- src/main/java/uk/gov/caz/psr/controller/exception/PaymentInfoPaymentMadeDateValidationException.java
- src/main/java/uk/gov/caz/psr/dto/PaymentInfoRequest.java
- src/main/java/uk/gov/caz/psr/dto/validation/constraint/AtLeastOneParameterPresentValidator.java
- src/main/java/uk/gov/caz/psr/model/PaymentInfoRequestAttributes.java
- src/main/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoService.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationByPaymentSubmittedDate.java
- src/main/java/uk/gov/caz/psr/util/PaymentInfoRequestConverter.java
- src/main/resources/application.yml
- src/main/resources/messages.properties
- src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
- src/test/java/uk/gov/caz/psr/dto/PaymentInfoRequestTest.java
- src/test/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoServiceTest.java
**Link to JIRA Card:**
* https://eaflood.atlassian.net/browse/CAZB-3285
**Screenshots:**
* ![Screenshot 2020-10-19 at 16 15 23](https://user-images.githubusercontent.com/4506633/96462871-62c3fa00-1226-11eb-95d6-9907fad46eef.png)
* ![Screenshot 2020-10-19 at 16 15 41](https://user-images.githubusercontent.com/4506633/96462971-7ff8c880-1226-11eb-9245-203abba5137f.png)
> [CAZB-3285] Adds paymentMadeDate to ChargeSettlement#payment-info

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTestIT.java
- src/main/java/uk/gov/caz/psr/controller/ChargeSettlementController.java
- src/main/java/uk/gov/caz/psr/controller/ExceptionController.java
- src/main/java/uk/gov/caz/psr/controller/exception/PaymentInfoPaymentMadeDateValidationException.java
- src/main/java/uk/gov/caz/psr/dto/PaymentInfoRequest.java
- src/main/java/uk/gov/caz/psr/dto/validation/constraint/AtLeastOneParameterPresentValidator.java
- src/main/java/uk/gov/caz/psr/model/PaymentInfoRequestAttributes.java
- src/main/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoService.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationByPaymentSubmittedDate.java
- src/main/java/uk/gov/caz/psr/util/PaymentInfoRequestConverter.java
- src/main/resources/application.yml
- src/main/resources/messages.properties
- src/test/java/uk/gov/caz/psr/controller/ChargeSettlementControllerTest.java
- src/test/java/uk/gov/caz/psr/dto/PaymentInfoRequestTest.java
- src/test/java/uk/gov/caz/psr/service/ChargeSettlementPaymentInfoServiceTest.java
> Update RC with selected commits

- src/main/resources/db/changelog/changes/0015-1.0-add-indexes-for-charge-settlement-endpoints.yaml
- src/main/resources/db/changelog/rawSql/0015-1.0-add-indexes-for-charge-settlement-endpoints.sql
Add indexes for charge settlement queries
> [CAZB-3457] Add indexes for charge settlement queries

- src/main/java/uk/gov/caz/psr/service/EntrantPaymentService.java
- src/test/java/uk/gov/caz/psr/service/EntrantPaymentServiceTest.java
Jira: https://eaflood.atlassian.net/browse/CAZB-3439
> [CAZB-3439] Fix issue when VEI records vehicle entrant in GMT for BST

- developer-resources/scripts/payments-test-data-sql-procedure/insert_test_payment_records.sql
Add test data generation SQL script
> [CAZB-3382] Add test data script to source control

- src/main/java/uk/gov/caz/psr/service/EntrantPaymentService.java
- src/test/java/uk/gov/caz/psr/service/EntrantPaymentServiceTest.java
Jira card: https://eaflood.atlassian.net/browse/CAZB-3439
> [CAZB-3439] Fix issue when tries to insert VehicleEntrant in UK time

- src/main/resources/application.yml
Remove Spring banner from logs
> [CAZB-3511] Remove Spring banner from logs

- src/main/java/uk/gov/caz/psr/repository/ExternalCardPaymentsRepository.java
> [CAZB-3312] Update payment description

- src/it/java/uk/gov/caz/psr/SuccessAddingVehicleEntrantIT.java
- src/it/resources/data/sql/add-entrant-payments.sql
- src/main/java/uk/gov/caz/psr/dto/EntrantPaymentWithLatestPaymentDetailsDto.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/VehicleEntrantControllerTest.java
- src/test/java/uk/gov/caz/psr/service/EntrantPaymentServiceTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
TariffCode to the POST `v1/payments/vehicle-entrants` endpoint.
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3433
> [CAZB-3433] Update entrants endpoint to return tariff code

- src/main/resources/db/changelog/changes/0017-1.0-additional-index-optimisation.yaml
- src/main/resources/db/changelog/rawSql/0017-1.0-additional-index-optimsation.sql
[CAZB-3457] Additional index optimisations against payment tables
> [CAZB-3457] Additional index optimisations

- src/main/resources/db/changelog/changes/0017-1.0-additional-index-optimisation.yaml
- src/main/resources/db/changelog/rawSql/0017-1.0-additional-index-optimsation.sql
Add further indexes for payment history optimisation
> [CAZB-3551] Add further indexes for payment history optimisation

- src/main/resources/db/changelog/changes/0018-1.0-additional-index-optimisation2.yaml
- src/main/resources/db/changelog/rawSql/0018-1.0-additional-index-optimsation.sql
Additional index optimisation for payment functions
> [CAZB-3551] Additional index optimisation for payment functions

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTest.java
- src/it/resources/data/sql/charge-settlement/payment-info/test-data.sql
- src/main/java/uk/gov/caz/psr/service/paymentinfo/PaymentInfoSpecificationByPaymentSubmittedDate.java
Jira card: https://eaflood.atlassian.net/browse/CAZB-3590
Fixed issue with UTC time zones while getting payment-info based on paymentMadeDate
> [CAZB-3590] payment-info with paymentMadeDate should return records in UTC timezone

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTest.java
- src/it/java/uk/gov/caz/psr/util/PaymentInfoAssertion.java
- src/main/java/uk/gov/caz/psr/util/EntrantPaymentInfoConverter.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3590
Fixed paymentDate calculation based on UK time.
> [CAZB-3590] Fix paymentDate in Uk time for payment Info

- developer-resources/scripts/delete-all-payment-data.sql
Add SQL script for clearing down payment data
> [CAZB-3546] Add SQL script for clearing down payment data

- src/it/java/uk/gov/caz/psr/RetrieveChargeableAccountVehiclesIT.java
- src/it/java/uk/gov/caz/psr/journeys/RetrieveChargeableAccountVehiclesJourneyAssertion.java
- src/it/resources/data/json/response/account-vehicles-empty-response.json
- src/main/java/uk/gov/caz/psr/dto/ChargeableAccountVehicleResponse.java
- src/main/java/uk/gov/caz/psr/model/ChargeableVehiclesPage.java
- src/main/java/uk/gov/caz/psr/service/AccountService.java
- src/main/java/uk/gov/caz/psr/service/ChargeableVehiclesService.java
- src/main/java/uk/gov/caz/psr/service/exception/AccountVehiclesBadRequest.java
- src/main/java/uk/gov/caz/psr/util/ChargeableVehiclesToDtoConverter.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3719
Additionally fixed bug when Accounts API returns 400 Bad Request response.
> [CAZB-3719] Expose anyUndeterminedVehicles in chargeableVehicles

- pom.xml
- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
[CAZB-3872] Spelling corrections
> [CAZB-3872] Spelling corrections

- src/it/java/uk/gov/caz/psr/directdebit/DirectDebitJourneyTestIT.java
- src/it/resources/data/external/directdebit/gocardless/complete-mandate-creation-response.json
- src/main/java/uk/gov/caz/psr/controller/DirectDebitMandatesController.java
- src/main/java/uk/gov/caz/psr/dto/CreateDirectDebitMandateRequest.java
- src/main/java/uk/gov/caz/psr/dto/accounts/CreateDirectDebitMandateRequest.java
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitMandatesService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/DirectDebitMandatesControllerTest.java
- src/test/java/uk/gov/caz/psr/service/directdebit/DirectDebitMandatesServiceTest.java
https://eaflood.atlassian.net/browse/CAZB-3692
> CAZB-3692 Parameter accountUserId added to mark the creator of Direct Debit

- src/it/resources/data/json/response/account-direct-debit-mandates-response.json
- src/it/resources/data/json/response/direct-debit-mandates-response.json
- src/main/java/uk/gov/caz/psr/dto/AccountDirectDebitMandatesResponse.java
- src/main/java/uk/gov/caz/psr/dto/directdebit/DirectDebitMandatesForCazResponse.java
- src/main/java/uk/gov/caz/psr/dto/directdebit/DirectDebitMandatesResponse.java
- src/main/java/uk/gov/caz/psr/model/directdebit/Mandate.java
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitMandatesService.java
- src/main/java/uk/gov/caz/psr/util/CleanAirZoneWithMandatesToDtoConverter.java
- src/main/java/uk/gov/caz/psr/util/MandatesToDtoConverter.java
Jira card: https://eaflood.atlassian.net/browse/CAZB-3687
> [CAZB-3687] Expose information about who set up a DD mandate

- src/main/resources/db/changelog/changes/0019-1.0-add-email-confirmation-sent-to-t-payment-table.yaml
- src/main/resources/db/changelog/rawSql/0019-1.0-add_email_confirmation_sent_to_t_payment.sql
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3905
> [CAZB-3905] Add email_confirmation_sent to T_PAYMENT table

- src/it/java/uk/gov/caz/psr/RetrieveChargeableAccountVehiclesIT.java
- src/it/java/uk/gov/caz/psr/directdebit/DirectDebitJourneyTestIT.java
- src/it/java/uk/gov/caz/psr/journeys/RetrieveChargeableAccountVehiclesJourneyAssertion.java
- src/it/resources/data/external/directdebit/gocardless/complete-mandate-creation-response.json
- src/it/resources/data/json/response/account-direct-debit-mandates-response.json
- src/it/resources/data/json/response/account-vehicles-empty-response.json
- src/it/resources/data/json/response/direct-debit-mandates-response.json
- src/main/java/uk/gov/caz/psr/controller/DirectDebitMandatesController.java
- src/main/java/uk/gov/caz/psr/dto/AccountDirectDebitMandatesResponse.java
- src/main/java/uk/gov/caz/psr/dto/ChargeableAccountVehicleResponse.java
- src/main/java/uk/gov/caz/psr/dto/CreateDirectDebitMandateRequest.java
- src/main/java/uk/gov/caz/psr/dto/accounts/CreateDirectDebitMandateRequest.java
- src/main/java/uk/gov/caz/psr/dto/directdebit/DirectDebitMandatesForCazResponse.java
- src/main/java/uk/gov/caz/psr/dto/directdebit/DirectDebitMandatesResponse.java
- src/main/java/uk/gov/caz/psr/model/ChargeableVehiclesPage.java
- src/main/java/uk/gov/caz/psr/model/directdebit/Mandate.java
- src/main/java/uk/gov/caz/psr/service/AccountService.java
- src/main/java/uk/gov/caz/psr/service/ChargeableVehiclesService.java
- src/main/java/uk/gov/caz/psr/service/directdebit/DirectDebitMandatesService.java
- src/main/java/uk/gov/caz/psr/service/exception/AccountVehiclesBadRequest.java
- src/main/java/uk/gov/caz/psr/util/ChargeableVehiclesToDtoConverter.java
- src/main/java/uk/gov/caz/psr/util/CleanAirZoneWithMandatesToDtoConverter.java
- src/main/java/uk/gov/caz/psr/util/MandatesToDtoConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/DirectDebitMandatesControllerTest.java
- src/test/java/uk/gov/caz/psr/service/directdebit/DirectDebitMandatesServiceTest.java
Update ST with latest release candidate/v1.8.0 content
> Update ST with latest release candidate/v1.8.0

- src/main/java/uk/gov/caz/psr/repository/AccountsRepository.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3703
Fixed params send to Accounts API for Chargeable vehicles.
> [CAZB-3703] Fix Chargeable Vehicles for CAZ

- src/it/java/uk/gov/caz/psr/PaymentReceiptSenderTestIT.java
- src/it/java/uk/gov/caz/psr/SuccessPaymentsJourneyTestIT.java
- src/it/java/uk/gov/caz/psr/repository/PaymentRepositoryTestIT.java
- src/main/java/uk/gov/caz/psr/model/Payment.java
- src/main/java/uk/gov/caz/psr/repository/PaymentRepository.java
- src/main/java/uk/gov/caz/psr/service/listener/PaymentReceiptSender.java
- src/test/java/uk/gov/caz/psr/repository/PaymentRepositoryTest.java
- src/test/java/uk/gov/caz/psr/service/listener/PaymentReceiptSenderTest.java
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3906
> [CAZB-3906] Populate email_confirmation_sent attribute

- pom.xml
Fixed ComplianceResutlsDto to return phgvDiscountAvailable value from the VCCS Proxy Controller.
> [CAZB-3869] Fix ComplianceResultsDto to support phgvDiscountAvailable value

- src/it/java/uk/gov/caz/psr/PaymentReceiptSenderTestIT.java
- src/it/java/uk/gov/caz/psr/SuccessPaymentsJourneyTestIT.java
- src/it/java/uk/gov/caz/psr/repository/PaymentRepositoryTestIT.java
- src/main/java/uk/gov/caz/psr/model/Payment.java
- src/main/java/uk/gov/caz/psr/repository/AccountsRepository.java
- src/main/java/uk/gov/caz/psr/repository/PaymentRepository.java
- src/main/java/uk/gov/caz/psr/service/listener/PaymentReceiptSender.java
- src/main/resources/db/changelog/changes/0019-1.0-add-email-confirmation-sent-to-t-payment-table.yaml
- src/main/resources/db/changelog/rawSql/0019-1.0-add_email_confirmation_sent_to_t_payment.sql
- src/test/java/uk/gov/caz/psr/repository/PaymentRepositoryTest.java
- src/test/java/uk/gov/caz/psr/service/listener/PaymentReceiptSenderTest.java
Resync release candidate/v1.8.0
> Resync release candidate/v1.8.0

- .drone2.yml
PRomote Payments v1.7.1 to Pre-Prod
> Promote Payments v1.7.1 to Pre-Prod

- pom.xml
- src/main/java/uk/gov/caz/psr/amazonaws/StreamLambdaHandler.java
Promote release v1.7.2 to Pre-production
> Promote release v1.7.2 to Pre-production

- src/it/java/uk/gov/caz/psr/VehiclePaymentHistoryControllerTestIT.java
- src/it/resources/data/sql/perform-la-update-to-charged-back.sql
- src/it/resources/data/sql/perform-la-update-to-refunded.sql
- src/main/java/uk/gov/caz/psr/model/EntrantPaymentEnriched.java
- src/main/java/uk/gov/caz/psr/model/PaymentStatusAuditData.java
- src/main/java/uk/gov/caz/psr/repository/audit/PaymentDetailRepository.java
- src/main/java/uk/gov/caz/psr/service/VehiclePaymentHistoryService.java
- src/main/resources/application.yml
- src/main/resources/db/changelog/changes/0022-1.0-add-index-to-clean-air-zone-payment-details-audit-table.yaml
- src/main/resources/db/changelog/rawSql/0022-1.0-add-index-to-clean-air-zone-payment-details-audit-table.sql
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-3912
* Ensuring index scan:
> [CAZB-3912] isRefunded and isChargedback added to payment history response

- src/it/java/uk/gov/caz/psr/PaymentHistoryByReferenceTestIT.java
- src/it/resources/data/sql/payment-history-by-reference/test-data.sql
- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/dto/ReferencesHistoryResponse.java
- src/main/java/uk/gov/caz/psr/model/EntrantPayment.java
- src/main/java/uk/gov/caz/psr/model/PaymentModification.java
- src/main/java/uk/gov/caz/psr/repository/audit/PaymentDetailRepository.java
- src/main/java/uk/gov/caz/psr/service/PaymentService.java
- src/main/java/uk/gov/caz/psr/util/ReferencesHistoryConverter.java
- src/main/resources/application.yml
- src/main/resources/db/changelog/changes/0023-1.0-add-index-for-reference-history-serach.yaml
- src/test/java/uk/gov/caz/psr/controller/PaymentsControllerTest.java
- src/test/java/uk/gov/caz/psr/service/PaymentServiceTest.java
- src/test/java/uk/gov/caz/psr/util/ReferencesHistoryConverterTest.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Jira card: https://eaflood.atlassian.net/browse/CAZB-3914
> [CAZB-3914] Add Refund/Chargeback history to the paymentReference endpoint

- src/it/java/uk/gov/caz/psr/PaymentInfoByOperatorIdTestIT.java
- src/it/resources/data/sql/payment-info-by-operator/test-data.sql
- src/main/java/uk/gov/caz/psr/dto/historicalinfo/PaymentsInfoByOperatorResponse.java
- src/main/java/uk/gov/caz/psr/model/EntrantPaymentEnriched.java
- src/main/java/uk/gov/caz/psr/model/PaymentAuditData.java
- src/main/java/uk/gov/caz/psr/model/PaymentModificationStatus.java
- src/main/java/uk/gov/caz/psr/model/info/byoperator/PaymentInfoByOperator.java
- src/main/java/uk/gov/caz/psr/repository/audit/PaymentDetailRepository.java
- src/main/java/uk/gov/caz/psr/service/VehiclePaymentHistoryService.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/byoperator/PaginatedPaymentsInfoByOperatorDetailsFetcher.java
- src/main/java/uk/gov/caz/psr/util/PaymentInfoByOperatorIdConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/repository/audit/PaymentDetailRepositoryTest.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3999
> [CAZB-3999] Return Refund/Chargeback flag in operators-history GET endpoint

- src/it/java/uk/gov/caz/psr/RetrieveSuccessfulPaymentsTestIT.java
- src/it/java/uk/gov/caz/psr/journeys/RetrieveSuccessfulPaymentsJourneyAssertion.java
- src/it/resources/data/sql/add-caz-entrant-payments.sql
- src/it/resources/data/sql/payment-history-by-reference/test-data.sql
- src/it/resources/data/sql/payment-info-by-operator/test-data.sql
- src/main/java/uk/gov/caz/psr/model/EnrichedPaymentSummary.java
- src/main/java/uk/gov/caz/psr/service/RetrieveSuccessfulPaymentsService.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/byoperator/PaginatedPaymentsInfoByOperatorDetailsFetcher.java
- src/test/java/uk/gov/caz/psr/service/RetrieveSuccessfulPaymentsServiceTest.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4135
> [CAZB-4135] Return Refund/Chargeback flag in GET /v1/accounts/{accountId}/payments

- pom.xml
- src/it/java/uk/gov/caz/psr/PaymentDetailsWithModificationHistoryTestIT.java
- src/it/resources/data/external/get-account-user-data.json
- src/it/resources/data/sql/payment-history-by-reference/test-data.sql
- src/main/java/uk/gov/caz/psr/controller/PaymentsController.java
- src/main/java/uk/gov/caz/psr/dto/ModificationHistoryDetails.java
- src/main/java/uk/gov/caz/psr/dto/PaymentDetailsResponse.java
- src/main/java/uk/gov/caz/psr/dto/ReferencesHistoryResponse.java
- src/main/java/uk/gov/caz/psr/repository/audit/PaymentDetailRepository.java
- src/main/java/uk/gov/caz/psr/service/PaymentService.java
- src/main/java/uk/gov/caz/psr/util/ModificationHistoryConverter.java
- src/main/java/uk/gov/caz/psr/util/PaymentDetailsConverter.java
- src/main/java/uk/gov/caz/psr/util/ReferencesHistoryConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/dto/ModificationHistoryDetailsTest.java
- src/test/java/uk/gov/caz/psr/dto/ReferencesHistoryResponseTest.java
- src/test/java/uk/gov/caz/psr/service/PaymentServiceTest.java
- src/test/java/uk/gov/caz/psr/util/PaymentDetailsConverterTest.java
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4134
> [CAZB-4134] Add refund and chargeback history to GET payment

- src/main/java/uk/gov/caz/psr/controller/CsvExportController.java
- src/main/java/uk/gov/caz/psr/controller/CsvExportControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/PaymentHistoryCsvExportResponse.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/controller/CsvExportControllerTest.java
Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4138
> [CAZB-4138] CSV export endpoint

- src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
- src/it/resources/data/csv/export/expected-payments-for-account-user.csv
- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/it/resources/data/sql/csv-export/test-data.sql
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGenerator.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTest.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4182?focusedCommentId=280295
> [CAZB-4139] Fix CSV data response

- pom.xml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4402
> [CAZB-4402] Update VCCS proxy endpoints to return new urls

- pom.xml
- src/test/java/uk/gov/caz/psr/service/CleanAirZoneServiceTest.java
https://eaflood.atlassian.net/browse/CAZB-4334
> [CAZB-4334] Update `clean-air-zones` endpoint to include new configuration items for dynamic display

- pom.xml
- src/test/java/uk/gov/caz/psr/service/CleanAirZoneServiceTest.java
JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4474
> [CAZB-4474] Update clean-air-zones proxy endpoint

- pom.xml
Update common libs to use new logger with request IDs
> [CAZB-4428] Update libs to use new logger with request IDs

- .drone2.yml
Add codedeploy steps for payment history to drone file
> [CAZB-4506] Add codedeploy steps for payment history

- src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
- src/it/java/uk/gov/caz/psr/service/generatecsv/CsvWriterTestIT.java
- src/it/resources/data/csv/export/expected-payments-for-account-user.csv
- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGenerator.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4625
> [CAZB-4625] Update column names for generated CSV file

- src/main/resources/db/changelog/changes/0025-1.0-new_payments_reporting_views.yaml
- src/main/resources/db/changelog/rawSql/0025-1.0-create-payments-reporting-views.sql
[CAZB-4488] Create new views for reporting
> [CAZB-4488] Create new views for reporting

- src/it/java/uk/gov/caz/psr/service/generatecsv/PaymentsHistoryCsvFileSupervisorTestIT.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGenerator.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGeneratorTest.java
https://eaflood.atlassian.net/browse/CAZB-4671
> [CAZB-4671] Update generated CSV file name

- src/it/java/uk/gov/caz/psr/service/generatecsv/PaymentsHistoryCsvFileSupervisorTestIT.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGenerator.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvUrlGenerator.java
- src/main/resources/db/changelog/changes/0025-1.0-new_payments_reporting_views.yaml
- src/main/resources/db/changelog/rawSql/0025-1.0-create-payments-reporting-views.sql
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGeneratorTest.java
Update release candidate with filename updates and expiry timer
>  [CAZB-4456, CAZB-4671, CAZB-4577] Update release candidate with filename updates and expiry timer

- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvWriter.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4717
> [CAZB-4717] Special Character displayed in Excel Download of Payment History

- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvWriter.java
Update RC 2.3.0 with CAZB-4717 fix
> [CAZB-4717] Special Character displayed in Excel Download of Payment History (#515)

- src/it/resources/application-integration-tests.yml
- src/main/java/uk/gov/caz/psr/configuration/RedisConfiguration.java
- src/main/resources/application.yml
Add SSL support for elasticache
> [CAZB-4691] Add SSL support for elasticache

- src/it/java/uk/gov/caz/psr/service/generatecsv/PaymentsHistoryCsvFileSupervisorTestIT.java
- src/it/resources/application-integration-tests.yml
- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/main/java/uk/gov/caz/psr/configuration/RedisConfiguration.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGenerator.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvWriter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGeneratorTest.java
Update Release candidate/v2.4.0
> Update Release candidate/v2.4.0

- src/it/java/uk/gov/caz/psr/SuccessPaymentsJourneyTestIT.java
- src/main/java/uk/gov/caz/psr/service/receipt/FleetPaymentReceiptRequestCreator.java
- src/test/java/uk/gov/caz/psr/service/receipt/FleetPaymentReceiptRequestCreatorTest.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4756
> [CAZB-4756] Alphabetical ordering of the VRN in email

- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGenerator.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvFileNameGeneratorTest.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4772
> [CAZB-4772] Payment History CSV timestamp needs to take into account of BST

- RUNNING_AND_TESTING.md
- src/it/java/uk/gov/caz/psr/PaymentInfoByDatesTestIT.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsInfoByOperatorController.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsInfoByOperatorControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/historicalinfo/PaymentsInfoByDatesRequest.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/bydates/PaginatedPaymentsInfoByDatesFetcher.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/bydates/PaymentsInfoByDatesService.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/byoperator/PaginatedPaymentsInfoByOperatorDetailsFetcher.java
- src/main/resources/application.yml
https://eaflood.atlassian.net/browse/CAZB-4660
> [CAZB-4660] Create GET "/payments/operators-history" API endpoint

- src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
- src/it/resources/data/csv/export/expected-payments-for-account-user.csv
- src/it/resources/data/sql/csv-export/test-data-without-la-updates.sql
- src/main/java/uk/gov/caz/psr/service/generatecsv/BaseCsvContentGeneratorStrategy.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGenerator.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategy.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategyFactory.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategy.java
- src/main/java/uk/gov/caz/psr/util/Strings.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/BaseCsvContentGeneratorStrategyTest.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategyFactoryTest.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategyTest.java
* JIRA Card - https://eaflood.atlassian.net/browse/CAZB-4835
> [CAZB-4835] Dynamic CSV file generation for payment history

- RUNNING_AND_TESTING.md
- src/it/java/uk/gov/caz/psr/PaymentInfoByDatesTestIT.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsInfoByOperatorController.java
- src/main/java/uk/gov/caz/psr/controller/PaymentsInfoByOperatorControllerApiSpec.java
- src/main/java/uk/gov/caz/psr/dto/historicalinfo/PaymentsInfoByDatesRequest.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/bydates/PaginatedPaymentsInfoByDatesFetcher.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/bydates/PaymentsInfoByDatesService.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/byoperator/PaginatedPaymentsInfoByOperatorDetailsFetcher.java
- src/main/resources/application.yml
[CAZB-4660] Create GET "/payments/operators-history" API endpoint (#530)
> [CAZB-4660] Create GET "/payments/operators-history" API endpoint (#530)

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTest.java
- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV1TestIT.java
- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV2TestIT.java
- src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
- src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
- src/it/java/uk/gov/caz/psr/SuccessPaymentStatusUpdateTestIT.java
- src/it/java/uk/gov/caz/psr/util/PaymentInfoAssertion.java
- src/it/resources/data/sql/add-payments-for-payment-status.sql
- src/it/resources/data/sql/charge-settlement/payment-info/test-data.sql
- src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentStatus.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
- src/main/java/uk/gov/caz/psr/model/InternalPaymentStatus.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-3876
> [CAZB-3876] Allow updating payment status to failed

- src/it/resources/data/sql/payment-history-by-reference/test-data.sql
- src/main/java/uk/gov/caz/psr/service/PaymentService.java
* JIRA card: https://eaflood.atlassian.net/browse/CAZB-4286
> [CAZB-4286] Include failed payments in payment details endpoint

- src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/it/resources/data/sql/csv-export/test-data.sql
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGenerator.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategy.java
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4266
> [CAZB-4266] update CSV to include failed payments

- src/it/java/uk/gov/caz/psr/PaymentInfoByDatesTestIT.java
- src/it/java/uk/gov/caz/psr/PaymentInfoByOperatorIdTestIT.java
- src/it/java/uk/gov/caz/psr/VehiclePaymentHistoryControllerTestIT.java
- src/it/resources/data/sql/payment-info-by-operator/test-data.sql
- src/it/resources/data/sql/perform-la-update-to-failed.sql
- src/main/java/uk/gov/caz/psr/dto/historicalinfo/PaymentsInfoByOperatorResponse.java
- src/main/java/uk/gov/caz/psr/model/EntrantPaymentEnriched.java
- src/main/java/uk/gov/caz/psr/model/InternalPaymentStatus.java
- src/main/java/uk/gov/caz/psr/model/info/byoperator/PaymentInfoByOperator.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/byoperator/PaginatedPaymentsInfoByOperatorDetailsFetcher.java
- src/main/java/uk/gov/caz/psr/util/PaymentInfoByOperatorIdConverter.java
- src/main/resources/application.yml
https://eaflood.atlassian.net/browse/CAZB-4313
https://eaflood.atlassian.net/browse/CAZB-4285
> [CAZB-4285][CAZB-4313] Add `isModified` to Payments historical endpoints in place of `isRefunded` and `isChargeBack`

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoTest.java
- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV1TestIT.java
- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV2TestIT.java
- src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
- src/it/java/uk/gov/caz/psr/GetChargeSettlementPaymentStatusTestIT.java
- src/it/java/uk/gov/caz/psr/PaymentInfoByDatesTestIT.java
- src/it/java/uk/gov/caz/psr/PaymentInfoByOperatorIdTestIT.java
- src/it/java/uk/gov/caz/psr/SuccessPaymentStatusUpdateTestIT.java
- src/it/java/uk/gov/caz/psr/VehiclePaymentHistoryControllerTestIT.java
- src/it/java/uk/gov/caz/psr/util/PaymentInfoAssertion.java
- src/it/resources/data/sql/add-payments-for-payment-status.sql
- src/it/resources/data/sql/charge-settlement/payment-info/test-data.sql
- src/it/resources/data/sql/payment-info-by-operator/test-data.sql
- src/it/resources/data/sql/perform-la-update-to-failed.sql
- src/main/java/uk/gov/caz/psr/dto/ChargeSettlementPaymentStatus.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
- src/main/java/uk/gov/caz/psr/dto/historicalinfo/PaymentsInfoByOperatorResponse.java
- src/main/java/uk/gov/caz/psr/model/EntrantPaymentEnriched.java
- src/main/java/uk/gov/caz/psr/model/InternalPaymentStatus.java
- src/main/java/uk/gov/caz/psr/model/info/byoperator/PaymentInfoByOperator.java
- src/main/java/uk/gov/caz/psr/service/paymentinfo/byoperator/PaginatedPaymentsInfoByOperatorDetailsFetcher.java
- src/main/java/uk/gov/caz/psr/util/PaymentInfoByOperatorIdConverter.java
- src/main/resources/application.yml
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
Promote latest release-candidate to ST for Payments API
> Promote latest release-candidate to ST for Payments API

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV2TestIT.java
- src/main/resources/messages.properties
https://eaflood.atlassian.net/browse/CAZB-4786
> [CAZB-4786] Adjust error message for charge settlement

- pom.xml
https://eaflood.atlassian.net/browse/CAZB-4967
> [CAZB-4967] SpringBoot upgrade to 2.4.6

- src/it/java/uk/gov/caz/psr/ChargeSettlementPaymentInfoV2TestIT.java
- src/main/resources/messages.properties
[CAZB-4786] Adjust error message for charge settlement (#542)
> [CAZB-4786] Adjust error message for charge settlement (#542)

- src/it/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorTestIT.java
- src/it/resources/data/csv/export/expected-payments-for-account-user.csv
- src/it/resources/data/csv/export/expected-payments-for-account.csv
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategy.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategyFactory.java
- src/main/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategy.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/BaseCsvContentGeneratorStrategyTest.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/CsvContentGeneratorStrategyFactoryTest.java
- src/test/java/uk/gov/caz/psr/service/generatecsv/LocalAuthorityCsvContentGeneratorStrategyTest.java
[CAZB-4835] Uppercasing of CSV download content and show failed payments
> [CAZB-4835] Uppercasing of CSV download content and show failed payments

- .gitignore
- src/it/java/uk/gov/caz/psr/ErrorPaymentStatusUpdateTestIT.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusRequest.java
- src/main/java/uk/gov/caz/psr/dto/PaymentStatusUpdateDetails.java
- src/test/java/uk/gov/caz/psr/util/TestObjectFactory.java
https://eaflood.atlassian.net/browse/CAZB-4905
> [CAZB-4905] Validate user input against blacklisted characters

- src/main/java/uk/gov/caz/psr/service/EntrantPaymentService.java
- src/test/java/uk/gov/caz/psr/service/EntrantPaymentServiceTest.java
https://eaflood.atlassian.net/browse/CAZB-4833
> [CAZB-4833] Update updateActor on entrant capture
